package com.feed_the_beast.ftbu.api.guide;

import com.feed_the_beast.ftbu.gui.guide.InfoPageGuide;
import net.minecraft.client.resources.IResourceManager;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.ModContainer;
import net.minecraftforge.fml.common.eventhandler.Event;

import java.util.Collections;
import java.util.Map;

public class ClientGuideEvent extends Event
{
    private final Map<String, IGuide> map;
    private final IResourceManager resourceManager;

    public ClientGuideEvent(Map<String, IGuide> m, IResourceManager r)
    {
        map = m;
        resourceManager = r;
    }

    public void add(IGuide page)
    {
        map.put(page.getPage().getName(), page);
    }

    public IGuide getModGuide(String modid)
    {
        ModContainer mod = Loader.instance().getIndexedModList().get(modid);

        IGuide guide;
        if(mod == null)
        {
            guide = new InfoPageGuide(modid, GuideType.MOD, Collections.emptyList(), Collections.singleton("Autogenerated"));
        }
        else
        {
            guide = new InfoPageGuide(mod);
        }

        add(guide);
        return guide;
    }

    public IResourceManager getResourceManager()
    {
        return resourceManager;
    }
}